config/routes.rb
Hacklendar::Application.routes.draw do

  resources :diary_entries

    root :to => 'diary_entries#index'

end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
	attr_accessible :title, :description, :mood	

	def self.allowed_types 
		['Happy', 'Sad', 'Angry', 'Delighted', 'Other']
	end

	validates :title, presence: true, uniqueness: true
	validates :description, presence: true
	validates :mood, presence: true, inclusion: { :in => DiaryEntry.allowed_types }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController
	http_basic_authenticate_with name: 'heather', password: 'hacklendarheather', except: :index

	def index
		if params[:date]
			@date = params[:date].to_date.to_time_in_current_zone
		else
			@date = Time.zone.now
		end
		@diary_entries = DiaryEntry.where(created_at: @date.beginning_of_day..@date.end_of_day)

		@diary_entry_month = DiaryEntry.where(created_at: @date.beginning_of_month..@date.end_of_month).map do |d|
			d.created_at.to_date
		end
	end

	def new
		@diary_entry = DiaryEntry.new
		
	end

	def create
		@diary_entry = DiaryEntry.new params[:diary_entry]

		if @diary_entry.save
		redirect_to diary_entries_path
		else 
			render :new
		end
	end

	def edit
    	@diary_entry = DiaryEntry.find(params[:id])
  	end

  	def update
  		@diary_entry = DiaryEntry.find(params[:id])

  		if @diary_entry.update_attributes params[:diary_entry]
  		   redirect_to diary_entries_path
  		else
  		   render :edit
  		end
  	end

  	def destroy
  		@diary_entry = DiaryEntry.find(params[:id])
  		@diary_entry.destroy
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/views/diary_entries/_calendar.html.erb
<div class="row" style="margin-top: 40px";>
<div class='calendar well'>
<div class="header lead" style="text-align: center";>
	<%= link_to "← ", diary_entries_path(date: @date.to_date - 1.month) %>
	<%= @date.strftime("%B %Y") %>
	<%= link_to " →", diary_entries_path(date: @date.to_date + 1.month) %>
</div>
<table class='titles'>
	<tr>
		<td class='day smallcaps'>
			Mon
		</td>
		<td class='day smallcaps'>
			Tue
		</td>
		<td class='day smallcaps'>
			Wed
		</td>
		<td class='day smallcaps'>
			Thu
		</td>
		<td class='day smallcaps'>
			Fri
		</td>
		<td class='day smallcaps'>
			Sat
		</td>
		<td class='day smallcaps'>
			Sun
		</td>
	</tr>
</table>
<table>
	<% (@date.beginning_of_month.beginning_of_week.to_date..@date.end_of_month.end_of_week.to_date).each do |date| %>
	<% if date.monday? %>
		<tr class="week"></div>
	<% end %>
	<td class="day">
		<%= link_to diary_entries_path(date: date), class: "link" do  %>
			<%= date.day %>
			<% if @diary_entry_month.include?(date) %>
			<div class="streak"></div>
			<% end %>
		<% end %>
	</td>
	<% end %>
</table>
</div><!-- calendar well -->
</div><!--row-->

app/views/diary_entries/_form.html.erb
<body id="contact-page">
<%= form_for(@diary_entry, :html => { :class => "form-signin"} ) do |f| %>
<h2>New Diary Entry</h2>
	
	<!--<div class="control-group warning">
	<% if @diary_entry.errors.any? %>
		<label class = "control-label" for "input warning">Something went wrong</label>
		<% @diary_entry.errors.full_messages.each do |error| %>
			<span class="help-inline"><%= error %></span>
		<% end %>
		</div>
	<% end %>
	</div>-->

 <div>
    <%= f.label :title %><%= f.text_field :title %>
 </div>
 <div>
    <%= f.label :description %><%= f.text_area :description, :rows => "5" %>
 </div>
 <div>
 	<%= f.label :mood %><%= f.select :mood, DiaryEntry.allowed_types, :prompt => 'Select One' %>
 </div>

 	<%= f.submit :class => "btn btn-primary" %> <p class="back">or go <%= link_to 'back', diary_entries_path %></p>
	<% end %>
</div>

app/views/diary_entries/edit.html.erb
<h1>Edit Your Diary Entry</h1>

<% render 'form' %>

<%= link_to 'Show', @diaryentry %> |
<%= link_to 'Back', diary_entries_path %>

app/views/diary_entries/index.html.erb
<div class="container">
    <div class="span6">
        <%= render "calendar" %>
    </div>
    <div class="span5">
        <h2><%= @date.strftime("%B %d %Y") %></h2>
        <p class='unstyled'>There are <%= @diary_entries.length %> posts today. Maybe you should add one<%=" more" if @diary_entries.length > 0 %>?</p>

        <%= link_to 'Add New Entry', new_diary_entry_path, :class => "btn btn-primary" %>

<% @diary_entries.each do |d| %>
        <p class="lead"><%= d.title %></p>
        <blockquote>
            <p><%= d.description %></p>
            <p class ="small">Today's mood: <%= d.mood %></p>
            <p class="smallcaps">Created <%= time_ago_in_words(d.created_at) %> ago</p>
        </blockquote>
    <!--<td><%= link_to 'Show', d %></td>
    <td><%= link_to 'Edit', edit_diary_entry_path(d) %></td>
    <td><%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<% end %>

<!--<% link_to "Previous Day", diary_entries_path(day: @date - 1.day) %>
<% link_to "Next Day", diary_entries_path(day: @date + 1.day) %>
<% link_to "New Diary Entry", new_diary_entry_path %>-->
    </div>
        </div>

app/views/diary_entries/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Heather's Hacklendar</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<style type="text/css">
    
	.week {
    clear: both;
  }
  .day {
    float: left;
    border-top: solid 1px #666;
    border-left: solid 1px #666;
    width: 68px;
    height: 68px;
    background: white;
    position: relative;
    cursor: pointer;
  }
  .week .day:last-child {
    border-right: solid 1px #666;
  }
  .calendar .week:last-child .day {
    border-bottom: solid 1px #666;
  }
  .week .day:nth-child(6), .week .day:last-child {
    background-color: #fafaff;
  }
  .calendar {
    width: 500px;
    padding: 10px;
    overflow: hidden;
  }
  .header {

  }
  .streak:after {
    content: '✓';
    font-size: 2.5em;
    position: absolute;
    right: 20px;
    bottom: 20px;
    color: #090;
  }

  h2 {
    font-size: 30px;
    line-height: 40px;
    margin-top: 50px;
  }

  .span5 {
    margin-left: -1px;
  }

  .lead {
    margin-top: 20px;
    margin-bottom: 10px;

  }

  .small {
    font-size:15px;
    color:#000000;
    line-height:20px;
    margin-bottom: 5px;
  }

  .smallcaps {
    font-size:10px;
    color:#939598;
    text-transform:uppercase;
    letter-spacing:1px;
    line-height:15px;
  }

  #contact-page {
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
  }

  .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }

  #contact-page h2 {
    margin-top: 0px;
  }

  input, textarea, .uneditable-input {
    width: 286px;
  }

  #contact-page p {
    margin: 0 0 10px;
  }

  .day a {
    display: block;
    height: 100%;
  }

  .titles .day {
    height: 10px;
    background: none;
    border: none;
    text-align: center;
    text-transform: uppercase;
    padding-bottom: 8px;
  }

  .link {
    padding: 5px;
  }

</style>

  </head>
  <body>
  		<%= yield %>
	</div>

  </body>
</html>